services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:9.2.3
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - critique

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:9.2.3
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - critique

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.4
    command:
      - start-dev
      - --db=dev-file
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=h2-file
    volumes:
      - keycloak-data:/opt/keycloak/data
    ports:
      - "9090:8080"
    networks:
      - critique

volumes:
  elasticsearch-data:
    driver: local
  keycloak-data:
    driver: local

networks:
  critique:
    driver: bridge